---
name: Build

on:
  - pull_request
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
        pio_board:
          - esp32cam
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install and update platformio
        run: |
          pip install -U platformio
          pio update

      - name: Build
        run: |
          sh gen_html_content.sh
          pio run -e ${{ matrix.pio_board }} -v
